#!/usr/bin/env python 
#
#  The MIT License (MIT)
#
# Copyright 2018 University of North Carolina at Chapel Hill. All other rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software
# and associated documentation files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or
# substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
# AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#

import subprocess
import json
import os
import sys
import signal

TIMEOUT=10
# top-level subroutine or function takes no arguments
# code for OpenC2 consumer
def main():
   # handle HTTP requests within 10s for UNIX/LINUX
   signal.signal(signal.SIGALRM, handler)
   signal.alarm(TIMEOUT)  
   # call function that will handle incoming requests from an OpenC2 producer
   request_handler()
   signal.alarm(0)

# alarm function to timeout requests
def handler(signum, frame):
   server_error(); 
   raise IOError("Couldn't open device!")

#function to handle GET, POST, cli request and to take some action
def request_handler():
   conformance=0
   openc2_actions=['query', 'deny', 'allow', 'update', 'delete']
   openc2_targets=['file', 'ip_addr', 'ip_connection', 'openc2', 'slpf']
   request=sys.stdin.read()
   parsed_json = json.loads(request)
   #do we have an actions var
   for alpha in openc2_actions:
      if alpha==parsed_json['action']:
         conformance += 1
   if conformance!=1:
      not_parseable()
   else: 
      conformance=0

   #do we have a targets var
   for beta in openc2_targets:
      if beta in parsed_json.get("target"):
         conformance += 1
   if conformance!=1:
      not_parseable()
   else:
      conformance=0
      execute_iptables("deny",parsed_json.get("target").get("ip_connection").get("src_addr"))
      server_ok('')

# tell producer something went wrong
def server_error():
   print('HTTP/1.1 500')
   print('Content-Type: application/openc2+json;version=1.0')
   print('')
   print(json.dumps(['response', {'status': (500), 'status_text': 'server error'}], sort_keys=True, indent=4))
   print('')

# tell producer we could not interpret request
def not_parseable():
   print('HTTP/1.1 400')
   print('Content-Type: application/openc2+json;version=1.0')
   print('')
   print(json.dumps(['response', {'status': (400), 'status_text': 'unable to parse request'}], sort_keys=True, indent=4))
   print('')

# tell producer things were ok
def server_ok(status_text):
   print('Content-Type: application/openc2+json;version=1.0')
   print('')
   print(json.dumps({'status': (200), 'status_text': 'ok'}, sort_keys=True, indent=4))
   print('')

# command to run iptables
# needs a lot of work, somewhere untrusted input validation needs to occur
# presently only supports denying a source IP 
def execute_iptables(action,source):
   if action=="deny":
      action_cli="DROP"
   # iptables command to review source IP and drop it if it is a match
   command_line_args=f"/sbin/iptables --append INPUT --source {source} --jump {action_cli}"
   result=subprocess.run(['sudo','/sbin/iptables','--append','INPUT','--source',source,'--jump',action_cli], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
   #server_ok(result.stdout)
   #server_ok(result.stderr)

if __name__ == "__main__":
    main()
